fix Kitchen script

diff --git a/Kitchen/kitchen b/Kitchen/kitchen
--- a/Kitchen/kitchen
+++ b/Kitchen/kitchen
@@ -11,6 +11,17 @@ DIR=$(pwd)
 CMD=$1
 BOOTIMG=$2
 
+check_termux() {
+    if [ -n "$PREFIX" ] && [ "$PREFIX" != "/" ]; then
+        MAGISKBOOT=$DIR/bin/magiskboot_android
+        TERMUX=1
+    else
+        MAGISKBOOT=$DIR/bin/magiskboot_linux
+        TERMUX=0
+    fi
+}
+check_termux
+
 AVBTOOL=$DIR/bin/avbtool
 
 chmod +x $DIR/bin/*
@@ -24,6 +35,28 @@ banner(){
 requirements(){
     if [ ! -z "$BOOTIMG" ]; then
         echo "$BOOTIMG" > "$DIR/res/.tmp1"
+    fi
+    set -e
+    if [ ! -f "$DIR/res/.req" ]; then
+        echo -e "${RED}[+] Installing Requirements...${RESET}\n"
+        if [ $TERMUX == 1 ]; then
+            pkg update -y > /dev/null 2>&1
+            echo -e "\n${GREEN}[i] OpenSSL${RESET}\n" ; pkg install openssl openssl-tool -y > /dev/null 2>&1
+            echo -e "\n${GREEN}[i] Python${RESET}\n" ; pkg install python -y > /dev/null 2>&1
+        elif [ $TERMUX == 0 ]; then
+            sudo apt update -y > /dev/null 2>&1
+            echo -e "\n${GREEN}[i] OpenSSL${RESET}\n" ; sudo apt install openssl -y > /dev/null 2>&1
+            echo -e "\n${GREEN}[i] Python${RESET}\n" ; sudo apt install python3 python-is-python3 -y > /dev/null 2>&1
+        else
+            echo -e "${BOLD_RED}[x] Error: Package manager not found.${RESET}"
+            exit 1
+        fi
+        echo -e "\n${RED}[i] Done...${RESET}\n"
+        echo "DON'T DELETE ME" > "$DIR/res/.req"
+    elif [ -f "$DIR/res/.req" ]; then
+        echo "" > /dev/null                       
+    else
+        echo -e "${BOLD_RED}[x] Error: Requirements installation failed.${RESET}"
     fi
 }
 
